export const UPDATE_DESIGNS ='UPDATE_DESIGNS';
export const UPDATE_USERS ='UPDATE_USERS';
export const UPDATE_CURRENT_USER ='UPDATE_CURRENT_USER';
export const UPDATE_LIKE ='UPDATE_LIKE';
export const ADD_CURRENT_LIKES ='ADD_CURRENT_LIKES';
export const REMOVE_CURRENT_LIKES ='REMOVE_CURRENT_LIKES';